// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const addCharacter = `-- name: AddCharacter :one
INSERT INTO characters(id, created_at, updated_at, name, card, is_user)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, deleted_at, name, card, is_user, is_system
`

type AddCharacterParams struct {
	Name   string
	Card   pqtype.NullRawMessage
	IsUser sql.NullBool
}

func (q *Queries) AddCharacter(ctx context.Context, arg AddCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, addCharacter, arg.Name, arg.Card, arg.IsUser)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Card,
		&i.IsUser,
		&i.IsSystem,
	)
	return i, err
}

const getCharactersLikeName = `-- name: GetCharactersLikeName :many
SELECT id FROM characters 
WHERE name LIKE $1
`

func (q *Queries) GetCharactersLikeName(ctx context.Context, name string) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getCharactersLikeName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCharactersLikeName = `-- name: GetUserCharactersLikeName :many
SELECT id, name, card FROM characters 
WHERE 
    name LIKE $1 AND
    is_user = 1
`

type GetUserCharactersLikeNameRow struct {
	ID   uuid.UUID
	Name string
	Card pqtype.NullRawMessage
}

func (q *Queries) GetUserCharactersLikeName(ctx context.Context, name string) ([]GetUserCharactersLikeNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserCharactersLikeName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserCharactersLikeNameRow
	for rows.Next() {
		var i GetUserCharactersLikeNameRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Card); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
