// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const addCharacter = `-- name: AddCharacter :one
INSERT INTO characters(id, created_at, updated_at, name, card, is_user)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, deleted_at, name, card, is_user, is_system
`

type AddCharacterParams struct {
	Name   string
	Card   json.RawMessage
	IsUser bool
}

func (q *Queries) AddCharacter(ctx context.Context, arg AddCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, addCharacter, arg.Name, arg.Card, arg.IsUser)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Card,
		&i.IsUser,
		&i.IsSystem,
	)
	return i, err
}

const getAvailableCharacters = `-- name: GetAvailableCharacters :many
SELECT id, name, card FROM characters
WHERE
    is_user = 'false' AND
    is_system = 'false' AND
    deleted_at IS NULL
`

type GetAvailableCharactersRow struct {
	ID   uuid.UUID
	Name string
	Card json.RawMessage
}

func (q *Queries) GetAvailableCharacters(ctx context.Context) ([]GetAvailableCharactersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAvailableCharactersRow
	for rows.Next() {
		var i GetAvailableCharactersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Card); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharactersLikeName = `-- name: GetCharactersLikeName :many
SELECT id FROM characters 
WHERE 
    name LIKE $1 AND
    deleted_at IS NULL
`

func (q *Queries) GetCharactersLikeName(ctx context.Context, name string) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getCharactersLikeName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCharactersLikeName = `-- name: GetUserCharactersLikeName :many
SELECT id, name, card FROM characters 
WHERE 
    name LIKE $1 AND
    is_user = 'true' AND
    deleted_at IS NULL
`

type GetUserCharactersLikeNameRow struct {
	ID   uuid.UUID
	Name string
	Card json.RawMessage
}

func (q *Queries) GetUserCharactersLikeName(ctx context.Context, name string) ([]GetUserCharactersLikeNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserCharactersLikeName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserCharactersLikeNameRow
	for rows.Next() {
		var i GetUserCharactersLikeNameRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Card); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharacterCard = `-- name: UpdateCharacterCard :exec
UPDATE characters
SET 
    updated_at = NOW(),
    card = $2
WHERE id = $1
`

type UpdateCharacterCardParams struct {
	ID   uuid.UUID
	Card json.RawMessage
}

func (q *Queries) UpdateCharacterCard(ctx context.Context, arg UpdateCharacterCardParams) error {
	_, err := q.db.ExecContext(ctx, updateCharacterCard, arg.ID, arg.Card)
	return err
}
