// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addCharacter = `-- name: AddCharacter :one
INSERT INTO characters(id, created_at, updated_at, name, system_prompt, is_user)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, deleted_at, name, system_prompt, is_user
`

type AddCharacterParams struct {
	Name         string
	SystemPrompt sql.NullString
	IsUser       sql.NullBool
}

func (q *Queries) AddCharacter(ctx context.Context, arg AddCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, addCharacter, arg.Name, arg.SystemPrompt, arg.IsUser)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.SystemPrompt,
		&i.IsUser,
	)
	return i, err
}

const getCharactersLikeName = `-- name: GetCharactersLikeName :many
SELECT id FROM characters 
WHERE name LIKE $1
`

func (q *Queries) GetCharactersLikeName(ctx context.Context, name string) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getCharactersLikeName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonasLikeName = `-- name: GetPersonasLikeName :many
SELECT id, name FROM characters 
WHERE 
    name LIKE $1 AND
    is_user = 1
`

type GetPersonasLikeNameRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) GetPersonasLikeName(ctx context.Context, name string) ([]GetPersonasLikeNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getPersonasLikeName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPersonasLikeNameRow
	for rows.Next() {
		var i GetPersonasLikeNameRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
