// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats_characters.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const subscribeToChat = `-- name: SubscribeToChat :one
INSERT INTO chat_subscriptions(id, chat_id, character_id)
VALUES(
    gen_random_uuid(),
    $1,
    $2
)
RETURNING id, chat_id, character_id
`

type SubscribeToChatParams struct {
	ChatID      uuid.UUID
	CharacterID uuid.UUID
}

func (q *Queries) SubscribeToChat(ctx context.Context, arg SubscribeToChatParams) (ChatSubscription, error) {
	row := q.db.QueryRowContext(ctx, subscribeToChat, arg.ChatID, arg.CharacterID)
	var i ChatSubscription
	err := row.Scan(&i.ID, &i.ChatID, &i.CharacterID)
	return i, err
}
