// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats_characters.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getCharactersLikeName = `-- name: GetCharactersLikeName :many
SELECT id FROM characters 
WHERE name LIKE $1
`

func (q *Queries) GetCharactersLikeName(ctx context.Context, name string) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getCharactersLikeName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscribeToChat = `-- name: SubscribeToChat :one
INSERT INTO chat_subscriptions(id, chat_id, character_id)
VALUES(
    gen_random_uuid(),
    $1,
    $2
)
RETURNING id, chat_id, character_id
`

type SubscribeToChatParams struct {
	ChatID      uuid.UUID
	CharacterID uuid.UUID
}

func (q *Queries) SubscribeToChat(ctx context.Context, arg SubscribeToChatParams) (ChatSubscription, error) {
	row := q.db.QueryRowContext(ctx, subscribeToChat, arg.ChatID, arg.CharacterID)
	var i ChatSubscription
	err := row.Scan(&i.ID, &i.ChatID, &i.CharacterID)
	return i, err
}
