// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_subscriptions.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const getCharactersInChat = `-- name: GetCharactersInChat :many
SELECT 
characters.id, 
characters.name,
characters.card
FROM chat_subscriptions 
INNER JOIN characters
    ON chat_subscriptions.character_id = characters.id
WHERE chat_subscriptions.chat_id = $1
`

type GetCharactersInChatRow struct {
	ID   uuid.UUID
	Name string
	Card pqtype.NullRawMessage
}

func (q *Queries) GetCharactersInChat(ctx context.Context, chatID uuid.UUID) ([]GetCharactersInChatRow, error) {
	rows, err := q.db.QueryContext(ctx, getCharactersInChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCharactersInChatRow
	for rows.Next() {
		var i GetCharactersInChatRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Card); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscribeToChat = `-- name: SubscribeToChat :exec
INSERT INTO chat_subscriptions(id, chat_id, character_id)
VALUES(
    gen_random_uuid(),
    $1,
    $2
)
`

type SubscribeToChatParams struct {
	ChatID      uuid.UUID
	CharacterID uuid.UUID
}

func (q *Queries) SubscribeToChat(ctx context.Context, arg SubscribeToChatParams) error {
	_, err := q.db.ExecContext(ctx, subscribeToChat, arg.ChatID, arg.CharacterID)
	return err
}
