// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_subscriptions.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getCharactersInChatByChatID = `-- name: GetCharactersInChatByChatID :many
SELECT chat_subscriptions.id, chat_id, character_id, characters.id, created_at, updated_at, deleted_at, name, system_prompt, is_user FROM chat_subscriptions 
INNER JOIN characters
    ON chat_subscriptions.character_id = characters.id
WHERE chat_subscriptions.chat_id = $1
`

type GetCharactersInChatByChatIDRow struct {
	ID           uuid.UUID
	ChatID       uuid.UUID
	CharacterID  uuid.UUID
	ID_2         uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
	Name         string
	SystemPrompt sql.NullString
	IsUser       sql.NullBool
}

func (q *Queries) GetCharactersInChatByChatID(ctx context.Context, chatID uuid.UUID) ([]GetCharactersInChatByChatIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getCharactersInChatByChatID, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCharactersInChatByChatIDRow
	for rows.Next() {
		var i GetCharactersInChatByChatIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.CharacterID,
			&i.ID_2,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.SystemPrompt,
			&i.IsUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharactersLikeName = `-- name: GetCharactersLikeName :many
SELECT id FROM characters 
WHERE name LIKE $1
`

func (q *Queries) GetCharactersLikeName(ctx context.Context, name string) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getCharactersLikeName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscribeToChat = `-- name: SubscribeToChat :exec
INSERT INTO chat_subscriptions(id, chat_id, character_id)
VALUES(
    gen_random_uuid(),
    $1,
    $2
)
`

type SubscribeToChatParams struct {
	ChatID      uuid.UUID
	CharacterID uuid.UUID
}

func (q *Queries) SubscribeToChat(ctx context.Context, arg SubscribeToChatParams) error {
	_, err := q.db.ExecContext(ctx, subscribeToChat, arg.ChatID, arg.CharacterID)
	return err
}
