// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addChat = `-- name: AddChat :one
INSERT INTO chats(id, created_at, updated_at, name)
VALUES(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1
)
RETURNING id, created_at, updated_at, deleted_at, name, user_character_id, card
`

func (q *Queries) AddChat(ctx context.Context, name string) (Chat, error) {
	row := q.db.QueryRowContext(ctx, addChat, name)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.UserCharacterID,
		&i.Card,
	)
	return i, err
}

const getAllChats = `-- name: GetAllChats :many
SELECT id, created_at, updated_at, deleted_at, name, user_character_id, card FROM chats
`

func (q *Queries) GetAllChats(ctx context.Context) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, getAllChats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.UserCharacterID,
			&i.Card,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardFromChatByID = `-- name: GetCardFromChatByID :one
SELECT card FROM chats
WHERE chats.id = $1
`

func (q *Queries) GetCardFromChatByID(ctx context.Context, id uuid.UUID) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getCardFromChatByID, id)
	var card sql.NullString
	err := row.Scan(&card)
	return card, err
}

const getChatByID = `-- name: GetChatByID :one
SELECT id, created_at, updated_at, deleted_at, name, user_character_id, card FROM chats
WHERE id = $1
`

func (q *Queries) GetChatByID(ctx context.Context, id uuid.UUID) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.UserCharacterID,
		&i.Card,
	)
	return i, err
}

const getChatsLikeName = `-- name: GetChatsLikeName :many
SELECT id, created_at, updated_at, deleted_at, name, user_character_id, card FROM chats
WHERE name LIKE $1
`

func (q *Queries) GetChatsLikeName(ctx context.Context, name string) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, getChatsLikeName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.UserCharacterID,
			&i.Card,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCharacterInChatByID = `-- name: GetUserCharacterInChatByID :one
SELECT id, name, card FROM characters
WHERE characters.id = (
    SELECT user_character_id 
    FROM chats
    WHERE chats.id = $1
)
`

type GetUserCharacterInChatByIDRow struct {
	ID   uuid.UUID
	Name string
	Card sql.NullString
}

func (q *Queries) GetUserCharacterInChatByID(ctx context.Context, id uuid.UUID) (GetUserCharacterInChatByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserCharacterInChatByID, id)
	var i GetUserCharacterInChatByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Card)
	return i, err
}
