// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const addChat = `-- name: AddChat :one
INSERT INTO chats(id, created_at, updated_at, name, card, user_character_id)
VALUES(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, deleted_at, name, user_character_id, card
`

type AddChatParams struct {
	Name            string
	Card            json.RawMessage
	UserCharacterID uuid.UUID
}

func (q *Queries) AddChat(ctx context.Context, arg AddChatParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, addChat, arg.Name, arg.Card, arg.UserCharacterID)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.UserCharacterID,
		&i.Card,
	)
	return i, err
}

const getAllChats = `-- name: GetAllChats :many
SELECT id, created_at, updated_at, deleted_at, name, user_character_id, card FROM chats
`

func (q *Queries) GetAllChats(ctx context.Context) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, getAllChats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.UserCharacterID,
			&i.Card,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableChats = `-- name: GetAvailableChats :many
SELECT id, name, card FROM chats
WHERE
    deleted_at IS NULL
`

type GetAvailableChatsRow struct {
	ID   uuid.UUID
	Name string
	Card json.RawMessage
}

func (q *Queries) GetAvailableChats(ctx context.Context) ([]GetAvailableChatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableChats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAvailableChatsRow
	for rows.Next() {
		var i GetAvailableChatsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Card); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardFromChatByID = `-- name: GetCardFromChatByID :one
SELECT card FROM chats
WHERE chats.id = $1
`

func (q *Queries) GetCardFromChatByID(ctx context.Context, id uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getCardFromChatByID, id)
	var card json.RawMessage
	err := row.Scan(&card)
	return card, err
}

const getChatByID = `-- name: GetChatByID :one
SELECT id, created_at, updated_at, deleted_at, name, user_character_id, card FROM chats
WHERE id = $1
`

func (q *Queries) GetChatByID(ctx context.Context, id uuid.UUID) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.UserCharacterID,
		&i.Card,
	)
	return i, err
}

const getChatsLikeName = `-- name: GetChatsLikeName :many
SELECT id, created_at, updated_at, deleted_at, name, user_character_id, card FROM chats
WHERE name LIKE $1
`

func (q *Queries) GetChatsLikeName(ctx context.Context, name string) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, getChatsLikeName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.UserCharacterID,
			&i.Card,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCharacterInChatByID = `-- name: GetUserCharacterInChatByID :one
SELECT id, name, card FROM characters
WHERE characters.id = (
    SELECT user_character_id 
    FROM chats
    WHERE chats.id = $1
)
`

type GetUserCharacterInChatByIDRow struct {
	ID   uuid.UUID
	Name string
	Card json.RawMessage
}

func (q *Queries) GetUserCharacterInChatByID(ctx context.Context, id uuid.UUID) (GetUserCharacterInChatByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserCharacterInChatByID, id)
	var i GetUserCharacterInChatByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Card)
	return i, err
}

const updateChatCard = `-- name: UpdateChatCard :one
UPDATE chats
SET 
    updated_at = NOW(),
    card = $2
WHERE id = $1
RETURNING id
`

type UpdateChatCardParams struct {
	ID   uuid.UUID
	Card json.RawMessage
}

func (q *Queries) UpdateChatCard(ctx context.Context, arg UpdateChatCardParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, updateChatCard, arg.ID, arg.Card)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
