// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addChat = `-- name: AddChat :one
INSERT INTO chats(id, created_at, updated_at, name)
VALUES(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1
)
RETURNING id, created_at, updated_at, deleted_at, name
`

func (q *Queries) AddChat(ctx context.Context, name string) (Chat, error) {
	row := q.db.QueryRowContext(ctx, addChat, name)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
	)
	return i, err
}

const getAllChats = `-- name: GetAllChats :many
SELECT id, created_at, updated_at, deleted_at, name FROM chats
`

func (q *Queries) GetAllChats(ctx context.Context) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, getAllChats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatByID = `-- name: GetChatByID :one
SELECT id, created_at, updated_at, deleted_at, name FROM chats
WHERE id = $1
`

func (q *Queries) GetChatByID(ctx context.Context, id uuid.UUID) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
	)
	return i, err
}

const getChatsLikeName = `-- name: GetChatsLikeName :many
SELECT id, created_at, updated_at, deleted_at, name FROM chats
WHERE name LIKE $1
`

func (q *Queries) GetChatsLikeName(ctx context.Context, name string) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, getChatsLikeName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
