// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addMessage = `-- name: AddMessage :one
INSERT INTO messages(id, created_at, updated_at, content_thoughts, content_answer, chat_id, author_id, role, idx)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    (SELECT COALESCE(MAX(idx), 0) + 1 FROM messages WHERE chat_id = $3)
)
RETURNING id, created_at, updated_at, deleted_at, content_thoughts, content_answer, chat_id, author_id, idx, role
`

type AddMessageParams struct {
	ContentThoughts sql.NullString
	ContentAnswer   string
	ChatID          uuid.UUID
	AuthorID        uuid.UUID
	Role            sql.NullString
}

func (q *Queries) AddMessage(ctx context.Context, arg AddMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, addMessage,
		arg.ContentThoughts,
		arg.ContentAnswer,
		arg.ChatID,
		arg.AuthorID,
		arg.Role,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ContentThoughts,
		&i.ContentAnswer,
		&i.ChatID,
		&i.AuthorID,
		&i.Idx,
		&i.Role,
	)
	return i, err
}

const deleteMessages = `-- name: DeleteMessages :exec
DELETE FROM messages
`

func (q *Queries) DeleteMessages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteMessages)
	return err
}

const getChatHistory = `-- name: GetChatHistory :many
SELECT messages.id, 
messages.content_thoughts, 
messages.content_answer,
messages.author_id,
messages.role,
characters.name AS author_name 
FROM messages
INNER JOIN characters
    ON messages.author_id = characters.id
WHERE messages.chat_id = $1
ORDER BY idx ASC
`

type GetChatHistoryRow struct {
	ID              uuid.UUID
	ContentThoughts sql.NullString
	ContentAnswer   string
	AuthorID        uuid.UUID
	Role            sql.NullString
	AuthorName      string
}

func (q *Queries) GetChatHistory(ctx context.Context, chatID uuid.UUID) ([]GetChatHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getChatHistory, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatHistoryRow
	for rows.Next() {
		var i GetChatHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ContentThoughts,
			&i.ContentAnswer,
			&i.AuthorID,
			&i.Role,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByChatID = `-- name: GetMessagesByChatID :many
SELECT id, created_at, updated_at, deleted_at, content_thoughts, content_answer, chat_id, author_id, idx, role FROM messages
WHERE chat_id = $1
ORDER BY idx ASC
`

func (q *Queries) GetMessagesByChatID(ctx context.Context, chatID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByChatID, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ContentThoughts,
			&i.ContentAnswer,
			&i.ChatID,
			&i.AuthorID,
			&i.Idx,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
