// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addMessage = `-- name: AddMessage :one
INSERT INTO messages(id, created_at, updated_at, content_thoughts, content_answer, chat_id, author_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, created_at, updated_at, deleted_at, content_thoughts, content_answer, chat_id, author_id
`

type AddMessageParams struct {
	ContentThoughts sql.NullString
	ContentAnswer   string
	ChatID          uuid.UUID
	AuthorID        uuid.UUID
}

func (q *Queries) AddMessage(ctx context.Context, arg AddMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, addMessage,
		arg.ContentThoughts,
		arg.ContentAnswer,
		arg.ChatID,
		arg.AuthorID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ContentThoughts,
		&i.ContentAnswer,
		&i.ChatID,
		&i.AuthorID,
	)
	return i, err
}
