// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Character struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	Name      string
	Card      pqtype.NullRawMessage
	IsUser    sql.NullBool
	IsSystem  sql.NullBool
}

type Chat struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
	Name            string
	UserCharacterID uuid.UUID
	Card            pqtype.NullRawMessage
}

type ChatSubscription struct {
	ID          uuid.UUID
	ChatID      uuid.UUID
	CharacterID uuid.UUID
}

type Message struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	Reasoning sql.NullString
	Content   string
	ChatID    uuid.UUID
	AuthorID  uuid.UUID
	Idx       sql.NullInt64
	Role      string
}
