// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Character struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	Name      string
	Card      json.RawMessage
	IsUser    bool
	IsSystem  bool
}

type Chat struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
	Name            string
	UserCharacterID uuid.UUID
	Card            json.RawMessage
}

type ChatSubscription struct {
	ID          uuid.UUID
	ChatID      uuid.UUID
	CharacterID uuid.UUID
}

type Message struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
	Reasoning   sql.NullString
	Content     string
	ChatID      uuid.UUID
	AuthorID    uuid.UUID
	Idx         int64
	Role        string
	ParentMsgID uuid.NullUUID
	SequenceIdx int64
}
