-- +goose Up
ALTER TABLE chats
ALTER COLUMN card SET NOT NULL, 
ALTER COLUMN card SET DEFAULT '{}'::jsonb;
ALTER TABLE characters
ALTER COLUMN card SET NOT NULL, 
ALTER COLUMN card SET DEFAULT '{}'::jsonb;

-- +goose Down
ALTER TABLE chats
ALTER COLUMN card DROP NOT NULL,
ALTER COLUMN card DROP DEFAULT;
ALTER TABLE characters
ALTER COLUMN card DROP NOT NULL,
ALTER COLUMN card DROP DEFAULT;